// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolutionBussines.DBRepository;

#nullable disable

namespace SolutionBussines.DBRepository.Migrations
{
    [DbContext(typeof(SBDbContext))]
    [Migration("20230316063044_FillTable")]
    partial class FillTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolutionBussines.Models.Db.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2023, 3, 16, 16, 30, 44, 185, DateTimeKind.Local).AddTicks(5896),
                            Number = "10-1",
                            ProviderId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2023, 3, 16, 16, 30, 44, 185, DateTimeKind.Local).AddTicks(5909),
                            Number = "10-2",
                            ProviderId = 1
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2023, 3, 16, 16, 30, 44, 185, DateTimeKind.Local).AddTicks(5912),
                            Number = "10-3",
                            ProviderId = 2
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2023, 3, 16, 16, 30, 44, 185, DateTimeKind.Local).AddTicks(5914),
                            Number = "10-41",
                            ProviderId = 1
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2023, 3, 16, 16, 30, 44, 185, DateTimeKind.Local).AddTicks(5915),
                            Number = "10-51",
                            ProviderId = 3
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2023, 3, 16, 16, 30, 44, 185, DateTimeKind.Local).AddTicks(5916),
                            Number = "10-6",
                            ProviderId = 5
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2023, 3, 16, 16, 30, 44, 185, DateTimeKind.Local).AddTicks(5917),
                            Number = "10-7",
                            ProviderId = 6
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2023, 3, 16, 16, 30, 44, 185, DateTimeKind.Local).AddTicks(5919),
                            Number = "10-8",
                            ProviderId = 6
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2023, 3, 16, 16, 30, 44, 185, DateTimeKind.Local).AddTicks(5920),
                            Number = "10-9",
                            ProviderId = 6
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2023, 3, 16, 16, 30, 44, 185, DateTimeKind.Local).AddTicks(5921),
                            Number = "10-11",
                            ProviderId = 7
                        });
                });

            modelBuilder.Entity("SolutionBussines.Models.Db.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Product_1",
                            OrderId = 1,
                            Quantity = 13m,
                            Unit = "unit_1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Product_11",
                            OrderId = 1,
                            Quantity = 13m,
                            Unit = "unit_1"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Product_111",
                            OrderId = 2,
                            Quantity = 13m,
                            Unit = "unit_1"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Product_12",
                            OrderId = 2,
                            Quantity = 13m,
                            Unit = "unit_1"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Product_122",
                            OrderId = 2,
                            Quantity = 13m,
                            Unit = "unit_1"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Product_13",
                            OrderId = 4,
                            Quantity = 13m,
                            Unit = "unit_1"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Product_133",
                            OrderId = 4,
                            Quantity = 13m,
                            Unit = "unit_1"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Product_14",
                            OrderId = 5,
                            Quantity = 13m,
                            Unit = "unit_1"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Product_144",
                            OrderId = 5,
                            Quantity = 13m,
                            Unit = "unit_1"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Product_15",
                            OrderId = 6,
                            Quantity = 13m,
                            Unit = "unit_1"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Product_155",
                            OrderId = 6,
                            Quantity = 13m,
                            Unit = "unit_1"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Product_16",
                            OrderId = 7,
                            Quantity = 13m,
                            Unit = "unit_1"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Product_166",
                            OrderId = 7,
                            Quantity = 13m,
                            Unit = "unit_1"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Product_17",
                            OrderId = 8,
                            Quantity = 13m,
                            Unit = "unit_1"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Product_177",
                            OrderId = 8,
                            Quantity = 13m,
                            Unit = "unit_1"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Product_18",
                            OrderId = 9,
                            Quantity = 13m,
                            Unit = "unit_1"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Product_188",
                            OrderId = 9,
                            Quantity = 13m,
                            Unit = "unit_1"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Product_19",
                            OrderId = 9,
                            Quantity = 13m,
                            Unit = "unit_1"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Product_199",
                            OrderId = 10,
                            Quantity = 13m,
                            Unit = "unit_1"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Product_10",
                            OrderId = 10,
                            Quantity = 13m,
                            Unit = "unit_1"
                        });
                });

            modelBuilder.Entity("SolutionBussines.Models.Db.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Providers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Provider_1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Provider_21"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Provider_3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Provider_4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Provider_5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Provider_6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Provider_7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Provider_8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Provider_9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Provider_10"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Provider_11"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Provider_12"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Provider_13"
                        });
                });

            modelBuilder.Entity("SolutionBussines.Models.Db.Order", b =>
                {
                    b.HasOne("SolutionBussines.Models.Db.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("SolutionBussines.Models.Db.OrderItem", b =>
                {
                    b.HasOne("SolutionBussines.Models.Db.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });
#pragma warning restore 612, 618
        }
    }
}
